[build]
  base = "frontend"
  publish = "frontend/dist"
  command = "npm run build"

[build.environment]
  VITE_API_URL = "https://novastream-backend.onrender.com"
  VITE_SOCKET_URL = "https://novastream-backend.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://novastream-backend.onrender.com"
  VITE_SOCKET_URL = "https://novastream-backend.onrender.com"